"""Arbitrage data models."""
from dataclasses import dataclass


@dataclass
class BasisData:
    """Current basis state for arbitrage."""
    timestamp: float
    spot_index: float           # KOSPI200 index
    futures_price: float        # Mini futures mid price
    fair_value: float           # Theoretical fair value
    basis: float                # futures - fair_value
    basis_zscore: float         # Standardized basis
    days_to_expiry: int
    rolling_mean: float
    rolling_std: float


@dataclass
class ArbitrageSignal:
    """Signal generated by ArbitrageEngine."""
    timestamp: float
    direction: str              # "BUY" or "SELL"
    basis_zscore: float
    entry_price: float          # Best bid (BUY) or best ask (SELL)
    order_size: float
    basis_data: BasisData
    rejection_reason: str | None = None
