"""Ensemble filter data models."""
from dataclasses import dataclass
from typing import Optional, List


@dataclass
class HorizonResult:
    """Result from a single prediction horizon."""
    horizon: str            # e.g., "1m", "5m", "15m"
    probability: float      # 0.0 to 1.0
    direction: str          # "LONG" or "SHORT"
    confirmed: bool         # Whether this horizon confirms the signal


@dataclass
class FilterResult:
    """Result from ensemble filter evaluation."""
    timestamp: float
    direction: str          # "LONG" or "SHORT"
    confidence: float       # Combined confidence score (0.0 to 1.0)
    dl_probability: float   # Raw DL model probability
    ma_aligned: bool        # MA crossover aligned with direction
    ichimoku_aligned: bool  # Ichimoku cloud aligned with direction
    volume_confirmed: bool  # Volume confirms the move

    # Optional multi-horizon data
    horizon_results: Optional[List[HorizonResult]] = None
    rejection_reason: Optional[str] = None

    def is_valid(self) -> bool:
        """Check if all filters are aligned for a valid signal."""
        return self.ma_aligned and self.ichimoku_aligned


@dataclass
class EnsembleSignal:
    """Trading signal generated by EnsembleFilter."""
    timestamp: float
    direction: str          # "LONG" or "SHORT"
    entry_price: float
    stop_loss: float
    take_profit: float
    position_size: float
    filter_result: FilterResult
    rejection_reason: Optional[str] = None
