"""Trend data models."""
from dataclasses import dataclass
from typing import Optional


@dataclass
class IchimokuData:
    """Ichimoku cloud indicator values."""
    tenkan: float           # Conversion line (9-period)
    kijun: float            # Base line (26-period)
    senkou_a: float         # Leading span A
    senkou_b: float         # Leading span B
    chikou: float           # Lagging span


@dataclass
class TechnicalData:
    """Technical indicator values for trend analysis."""
    timestamp: float
    close: float

    # Moving averages
    ma_short: float
    ma_long: float

    # Ichimoku components
    ichimoku_tenkan: float
    ichimoku_kijun: float
    ichimoku_senkou_a: float
    ichimoku_senkou_b: float

    # Volatility
    atr: float

    # Optional extended data
    ma_trend: Optional[float] = None  # MA slope
    volume_ratio: Optional[float] = None


@dataclass
class TrendSignal:
    """Signal generated by TrendEngine."""
    timestamp: float
    direction: str          # "LONG" or "SHORT"
    confidence: float       # 0.0 to 1.0
    entry_price: float
    stop_loss: float
    take_profit: float
    technical_data: TechnicalData
    rejection_reason: Optional[str] = None
